image: node:10.15.0 # change to match your node version

cache:
  paths:
    - node_modules/

before_script:
  - yarn install

developBuild:
  stage: deploy
  script:
    - CI=false yarn run build #CI=false so warnings are not treated as errors
  only:
    - develop

pages:
  stage: deploy
  script:
    - CI=false yarn run build #CI=false so warnings are not treated as errors
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public # GitLab pages serve from a 'public' directory
  only:
    - master # run on master branch
